// examples/helloworld/src/App.svelte
<script>
  import { invoke } from "@tauri-apps/api/core"
  import Greet from './lib/Greet.svelte'

	function _panic() {
		invoke("this_will_panic")
	}
</script>

<main class="container">
  <h1>Welcome to Tauri!</h1>

  <div class="row">
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo vite" alt="Vite Logo" />
    </a>
    <a href="https://tauri.app" target="_blank">
      <img src="/tauri.svg" class="logo tauri" alt="Tauri Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank">
      <img src="/svelte.svg" class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>

  <p>
    Click on the Tauri, Vite, and Svelte logos to learn more.
  </p>

  <div class="row">
    <Greet />
  </div>

  <div>
    <button on:click="{_panic}">PANIC!</button>
  </div>

</main>

<style>
  .logo.vite:hover {
    filter: drop-shadow(0 0 2em #747bff);
  }

  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00);
  }
</style>

// examples/helloworld/src/App.tsx
import reactLogo from "./assets/react.svg";
import { trackEvent } from '@aptabase/tauri'
import "./App.css";
import { invoke } from "@tauri-apps/api";

function App() {
  function clickVite() {
    trackEvent("logo_click", { "logo": "vite", count: 1 })
  }

  function clickTauri() {
    trackEvent("logo_click", { "logo": "tauri", count: 1 })
  }

  function clickReact() {
    trackEvent("logo_click", { "logo": "react", count: 1 })
  }

  function panic() {
    invoke("this_will_panic")
  }

  return (
    <div className="container">
      <h1>Welcome to Tauri + Aptabase Example!</h1>

      <div className="row">
        <button onClick={clickVite}>
          <img src="/vite.svg" className="logo vite" alt="Vite logo" />
        </button>
        <button onClick={clickTauri}>
          <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
        </button>
        <button onClick={clickReact}>
          <img src={reactLogo} className="logo react" alt="React logo" />
        </button>
      </div>

      <p>Click on the Tauri, Vite, and React logos to trigger an event.</p>

      <div>
        <button onClick={panic}>PANIC!</button>
      </div>
    </div>
  );
}

export default App;
